spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfm
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create

  web:
    resources:
      static-locations: classpath:/static/
